In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('Studentsperformance.csv')

In [3]:
# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1  Selecting two or more columns

In [5]:
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [6]:
# check out the data type of te selection
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [7]:
# select 2 or more columns using [[]]

# 1 Adding a new Column to dataframe

### 1.1 Adding a new column  with a scalar value

In [10]:
# adding new colum to dataframe
df_exams ['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

### 1.2  Adding a new column with an array


The dataframe has 1000 rows , so we need to create an array with 1000 elements

In [12]:
import numpy as np

In [13]:
# create an array of 1000 elements
language_score = np.arange(0,1000)

In [14]:
 #  lent of the array
len(language_score)

1000

In [15]:
# adding a new column to dataframe with an array
df_exams['language score']  = language_score

In [16]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [17]:
# create array of  random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size = 1000)
len(language_score)

1000

In [18]:
# min value inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

99

In [19]:
# adding a new column to dataframe with an array
df_exams['language score']  = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,27
1,female,group C,some college,standard,completed,69,90,88,37
2,female,group B,master's degree,standard,none,90,95,93,11
3,male,group A,associate's degree,free/reduced,none,47,57,44,38
4,male,group C,some college,standard,none,76,78,75,46
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,32
996,male,group C,high school,free/reduced,none,62,55,55,11
997,female,group C,high school,free/reduced,completed,59,71,65,84
998,female,group D,some college,standard,completed,68,78,77,42
999,female,group D,some college,free/reduced,none,77,86,86,20

In [20]:
# create random float numbers between 1 and 100
np.random.uniform(1,100, size =100)

array([70.03128706, 92.32338141, 13.59568951,  1.92196438, 44.95775981,
       52.66552302, 17.48931794, 98.18449449, 15.2470255 , 96.26526021,
       92.71663867, 42.35076103, 56.69700363, 87.84288866, 92.26969268,
       74.89826137, 81.73599861, 88.24511994, 57.55667193, 52.25404323,
        2.51054834, 89.5717102 , 92.0621821 ,  6.11448777, 83.43837253,
       68.85948542, 71.81980181, 45.52606947, 83.06200758, 26.32693055,
       74.17010503, 53.27547487, 86.77904035, 72.49017028, 12.17098764,
       26.83693715, 42.75761782, 52.26843025, 13.5703452 ,  5.94339806,
       46.23788125, 19.04266991, 50.40984418, 13.84914211, 55.61567801,
       47.90892431, 64.47898325,  6.8607715 , 68.0298435 , 96.86170074,
       91.85613578, 96.33121849, 64.17126139, 52.15176836,  1.98833144,
       88.23101232, 20.86797876, 45.86013607, 60.19192267, 22.39524701,
       37.98829888, 84.80630613, 86.99425017, 33.08348398,  2.37652415,
       28.98118462,  2.31885249,  7.93583423, 78.19983016, 88.47332161,
       44.45842038,  8.71020563, 81.22867142, 99.639586  , 27.96058309,
       58.34779786, 94.67434412, 70.54176887, 40.96578507, 39.5240274 ,
       51.30829667, 40.2144436 , 54.7282664 , 43.17646244, 19.42768966,
       47.48733602, 19.09663556, 19.02584351, 89.98859094, 41.13933913,
       33.81741085, 68.1058225 , 51.03977134, 96.03585245, 61.71638533,
       94.46172013, 19.74907981, 93.35728014, 89.25679488, 12.54656694])

### 1.2 assign()

When  to use assign?
  
  - Add multiple columns in a single line of code.
  - when  you need to overwrite  the values of an existing columns(best practice)

 it returns a new object (a copy) with all the original columns in addition to the new ones

In [22]:
import numpy as np

In [23]:
#create random numbers for our new score  columns
score1 = np.random.randint(1, 100, size =1000)
score2 = np.random.randint(1, 100, size =1000)

In [24]:
# create a series using the random numbers
series1 =pd.Series(score1, index=np.arange(0,  1000))
series2 =pd.Series(score2, index=np.arange(0,  1000))

In [25]:
series1, series2

(0      16
 1      40
 2      55
 3      95
 4      34
        ..
 995    14
 996    44
 997    64
 998    74
 999    76
 Length: 1000, dtype: int32,
 0      77
 1      34
 2      43
 3      12
 4      19
        ..
 995    35
 996    21
 997    21
 998    43
 999    19
 Length: 1000, dtype: int32)

In [26]:
# using assign () to add multiple columns
df_exams= df_exams.assign(score1=series1,  score2=series2)

In [27]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,27,16,77
1,female,group C,some college,standard,completed,69,90,88,37,40,34
2,female,group B,master's degree,standard,none,90,95,93,11,55,43
3,male,group A,associate's degree,free/reduced,none,47,57,44,38,95,12
4,male,group C,some college,standard,none,76,78,75,46,34,19
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,32,14,35
996,male,group C,high school,free/reduced,none,62,55,55,11,44,21
997,female,group C,high school,free/reduced,completed,59,71,65,84,64,21
998,female,group D,some college,standard,completed,68,78,77,42,74,43
999,female,group D,some college,free/reduced,none,77,86,86,20,76,19

###  1.2 insert()

Inserts a new column at a specific position or index.

In [29]:
#  using index()  to add a column at a specific position , this works direct without =
df_exams.insert(1, 'test' , series1)

In [58]:
#  show the dataframe
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,16,group B,bachelor's degree,standard,none,72,72,74,27,16,77
1,female,40,group C,some college,standard,completed,69,90,88,37,40,34
2,female,55,group B,master's degree,standard,none,90,95,93,11,55,43
3,male,95,group A,associate's degree,free/reduced,none,47,57,44,38,95,12
4,male,34,group C,some college,standard,none,76,78,75,46,34,19
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,14,group E,master's degree,standard,completed,88,99,95,32,14,35
996,male,44,group C,high school,free/reduced,none,62,55,55,11,44,21
997,female,64,group C,high school,free/reduced,completed,59,71,65,84,64,21
998,female,74,group D,some college,standard,completed,68,78,77,42,74,43
999,female,76,group D,some college,free/reduced,none,77,86,86,20,76,19